services:
  keepalive:
    image: ghcr.io/eidodk/keepalive:latest
    container_name: keepalive
    restart: unless-stopped

    environment:
      TARGET: "192.168.1.100"          # Edit to change patient
      INTERVAL: "21600"                # How often do you do rounds (21600 = every 6 hours)
      LOGFILE: "/logs/keepalive.log"   # Where do you keep this journal

    # persistent logs:
    volumes:
      - ./logs:/logs

    # Use custom log names for multiple patients:
    #
    # LOGFILE: "/logs/camera.log"
    # LOGFILE: "/logs/doorbell.log"
    # LOGFILE: "/logs/whatever.log"